[package]
name = "rmk-q6_he_ansi"
version = "0.8.0"
description = "Keyboard firmware written in Rust"
homepage = "https://github.com/haobogu/rmk"
repository = "https://github.com/haobogu/rmk"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
cortex-m = { version = "0.7", features = ['critical-section-single-core'] }
cortex-m-rt = "0.7"
embassy-time = { version = "0.5", features = ["tick-hz-32_768"] }
embassy-stm32 = { version = "0.5", features = ["stm32f401rc", "memory-x", "time-driver-any", "exti"] }
embassy-executor = { version = "0.9", features = [ "arch-cortex-m", "executor-thread"] }
embedded-storage = "0.3"
heapless = "0.9"
rmk = { version = "0.8", default-features = false, features = ["storage", "async_matrix", "vial", "vial_lock"] }
static_cell = "2"

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"

[[bin]]
name = "rmk-q6_he_ansi"
test = false
bench = false

[profile.dev]
codegen-units = 1      # better optimizations
debug = true
opt-level = 1
overflow-checks = true
lto = false
panic = 'unwind'

[profile.release]
codegen-units = 1       # better optimizations
debug = true
strip = "symbols"
opt-level = "z"         # optimize for binary size
overflow-checks = false
lto = "fat"
panic = "abort"
